image: node:16-alpine


stages:
  - install
  - unit-testing
  - e2e-testing
  - build
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        _ENV: production
        _FIREBASE_DEPLOYMENT: deploy --only hosting
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        _ENV: staging
        _FIREBASE_DEPLOYMENT: hosting:channel:deploy $CI_ENVIRONMENT_NAME

.install_cache: 
  cache: &install_cache
    key: ${CI_COMMIT_REF_SLUG}-install
    paths:
      - .yarn/
      - node_modules/
    policy: pull

.build_cache: 
  cache: &build_cache
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - public/
      - .cache/
    policy: pull

.firebase_tools_cache:
  cache: &firebase_tools_cache
    key: ${CI_COMMIT_REF_SLUG}-build
    paths:
      - /usr/local/bin/firebase
    policy: pull-push

install:
  stage: install
  environment: $_ENV
  script:
    - echo 'Installing dependencies:'
    - yarn set version berry
    - yarn install
  cache:
    - <<: *install_cache
      policy: pull-push
  rules:
    - if: $STRAPI_UPDATE != "true"

unit-testing:
  stage: unit-testing
  environment: $_ENV
  script:
    - echo "Starting Unit Tests"
    - yarn test

  cache:
    - <<: *install_cache
  rules:
    - if: $STRAPI_UPDATE != "true"

e2e-testing:
  stage: e2e-testing
  environment: $_ENV
  script:
    - echo "Starting e2e Tests"
    - yarn e2e
  cache:
    - <<: *install_cache
  rules:
    - if: $_ENV == 'production' && $STRAPI_UPDATE != "true"
include:
  - local: Secret-Detection.gitlab-ci.yml
    rules:
      - if: $_ENV == 'production' && $STRAPI_UPDATE != "true"
  - local: Security/SAST.gitlab-ci.yml
    rules:
      - if: $_ENV == 'production' && $STRAPI_UPDATE != "true"

build:
  stage: build
  environment:
    name: $_ENV
  script:
    - yarn build
  cache:
    - <<: *build_cache 
      policy: pull-push
    - <<: *install_cache     

deploy:
  stage: deploy
  environment:
    name: $_ENV
  cache:
    - <<: *build_cache
    - <<: *firebase_tools_cache
  script:
    - wget firebase.tools -O /tmp/some_file && cat /tmp/some_file | ash
    - echo "Deploying to Firebase in $CI_ENVIRONMENT_NAME"
    - firebase $_FIREBASE_DEPLOYMENT --token $FIREBASE_TOKEN
