image: docker:latest

# include:
#   - template: Secret-Detection.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml

stages:
  # - test
  - deploy

deploy:
  stage: deploy
  image: node:14
  before_script:
    - npm i -g firebase-tools
  script:
    - echo "Deploying to Firebase"
    - npm install
    - npm run build
    - firebase deploy --token $FIREBASE_TOKEN
