image: docker:latest

# include:
#   - template: Secret-Detection.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

stages:
  # - test
  - deploy

deploy:
  stage: deploy
  image: node:14
  before_script:
    - npm i -g firebase-tools
  script:
    - echo "Deploying to Firebase"
    - npm install
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH === $CI_DEFAULT_BRANCH
      variables:
        _ENV: staging
      script:
        - NODE_ENV=$_ENV node firebase hosting:channel:deploy $_ENV --token $FIREBASE_TOKEN