image: node:14-stretch

# include:
#   - template: Secret-Detection.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - npm i -g firebase-tools
  script:
    - echo 'Installing dependencies:'
    - yarn set version berry
    - yarn install
  artifacts:
    paths:
    - .yarn/
    - node_modules/
    - yarn.lock
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn/
      - node_modules/

test:
  stage: test
  script:
    - echo "Starting Test"
    - yarn test

deploy:
  stage: deploy
  environment:
    name: $_ENV
  script:
    - echo "Deploying to Firebase in $CI_ENVIRONMENT_NAME"
    - yarn build
    - firebase $_FIREBASE_DEPLOYMENT --token $FIREBASE_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        _ENV: production
        _FIREBASE_DEPLOYMENT: deploy --only hosting
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        _ENV: staging
        _FIREBASE_DEPLOYMENT: hosting:channel:deploy $CI_ENVIRONMENT_NAME