image: docker:latest

include:
  - template: Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

  stages:
    - deploy

  deploy:
    stage: deploy
    image: node14-alpine
    before_script:
      - npm i -g firebase-tools
    script:
      - echo "Deploying to Firebase"
      - npm run build
      - firebase deploy --token $FIREBASE_TOKEN