image: docker:latest

# include:
#   - template: Secret-Detection.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml

stages:
  # - test
  - deploy

deploy:
  stage: deploy
  image: mhart/alpine-node:14
  before_script:
    - npm i -g firebase-tools
  environment:
    name: $_ENV
  script:
    - echo "Installing Yarn"
    - npm install -g yarn@berry
    - yarn install
    - yarn build
    - echo "Deploying to Firebase in $CI_ENVIRONMENT_NAME"
    - firebase $_FIREBASE_DEPLOYMENT --token $FIREBASE_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        _ENV: production
        _FIREBASE_DEPLOYMENT: deploy --only hosting
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        _ENV: staging
        _FIREBASE_DEPLOYMENT: hosting:channel:deploy $CI_ENVIRONMENT_NAME