image: node:14-stretch

# include:
#   - template: Secret-Detection.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        _ENV: production
        _FIREBASE_DEPLOYMENT: deploy --only hosting
    - if: $CI_COMMIT_BRANCH == "staging"
      variables:
        _ENV: staging
        _FIREBASE_DEPLOYMENT: hosting:channel:deploy $CI_ENVIRONMENT_NAME

build:
  stage: build
  environment:
    name: $_ENV
  script:
    - echo 'Installing dependencies:'
    - yarn set version berry
    - yarn install
    - yarn build
  artifacts:
    paths:
      - .yarn
      - node_modules/
      - public/
      - .cache/
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .yarn/
      - node_modules/
      - public/
      - .cache/

test:
  stage: test
  script:
    - echo "Starting Tests"
    - yarn test
  rules:
    - if: $_ENV == "production"

deploy:
  stage: deploy
  environment:
    name: $_ENV
  before_script:
    - npm i -g firebase-tools
  script:
    - echo "Deploying to Firebase in $CI_ENVIRONMENT_NAME"
    - firebase $_FIREBASE_DEPLOYMENT --token $FIREBASE_TOKEN
