image: docker:latest

# include:
#   - template: Secret-Detection.gitlab-ci.yml
#   - template: Security/SAST.gitlab-ci.yml

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

stages:
  # - test
  - deploy

deploy-staging:
  stage: deploy
  image: node:14
  before_script:
    - npm i -g firebase-tools
  environment:
    name: staging
  script:
    - echo "Deploying to Firebase"
    - npm install
    - npm run build
    - firebase hosting:channel:deploy $CI_ENVIRONMENT_NAME --token $FIREBASE_TOKEN
  rules:
    - if: $CI_COMMIT_BRANCH === $CI_ENVIRONMENT_NAME